// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DataAccessLayer.Models;

public partial class Application
{
    public int ApplicationId { get; set; }

    public DateOnly CreationDate { get; set; }

    public string Status { get; set; }

    public sbyte ApplicationType { get; set; }

    public string ApplicationDescription { get; set; }

    public int CreatedByUser { get; set; }

    public virtual ICollection<Consumablespurchaseorder> Consumablespurchaseorders { get; set; } = new List<Consumablespurchaseorder>();

    public virtual ICollection<Consumableswithdrawapplication> Consumableswithdrawapplications { get; set; } = new List<Consumableswithdrawapplication>();

    public virtual User CreatedByUserNavigation { get; set; }

    public virtual ICollection<Sparepartspurchaseorder> Sparepartspurchaseorders { get; set; } = new List<Sparepartspurchaseorder>();
    [JsonIgnore]
    public virtual ICollection<Sparepartswithdrawapplication> Sparepartswithdrawapplications { get; set; } = new List<Sparepartswithdrawapplication>();
}