// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Bus
{
    public sbyte BusId { get; set; }

    public sbyte Capacity { get; set; }

    public sbyte AvailableSpace { get; set; }

    public short VehicleId { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}