// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DataAccessLayer.Models;

public partial class Consumablespurchaseorder
{
    public int OrderId { get; set; }

    public int ApplicationId { get; set; }

    public sbyte RequiredItem { get; set; }

    public short RequiredQuantity { get; set; }

    public bool ApprovedByGeneralSupervisor { get; set; }

    public bool ApprovedByGeneralManager { get; set; }
    [JsonIgnore]
    public virtual Application Application { get; set; }

    public virtual Vehicleconsumable RequiredItemNavigation { get; set; }
}