// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public string NationalNo { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public bool IsAbsent { get; set; }

    public bool IsAvailable { get; set; }

    public short VehicleId { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}