// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Sparepartsreplacement
{
    public int ReplacementId { get; set; }

    public int MaintenanceId { get; set; }

    public short SparePartId { get; set; }

    public virtual Sparepart SparePart { get; set; }
}