// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Sparepart
{
    public short SparePartId { get; set; }

    public string PartName { get; set; }

    public int ValidityLength { get; set; }

    public short Quantity { get; set; }

    public virtual ICollection<Sparepartspurchaseorder> Sparepartspurchaseorders { get; set; } = new List<Sparepartspurchaseorder>();

    public virtual ICollection<Sparepartsreplacement> Sparepartsreplacements { get; set; } = new List<Sparepartsreplacement>();

    public virtual ICollection<Sparepartswithdrawapplication> Sparepartswithdrawapplications { get; set; } = new List<Sparepartswithdrawapplication>();
}