// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Sparepartswithdrawapplication
{
    public int WithdrawApplicationId { get; set; }

    public int ApplicationId { get; set; }

    public short SparePartId { get; set; }

    public short VehicleId { get; set; }

    public bool ApprovedByGeneralSupervisor { get; set; }

    public bool ApprovedByGeneralManager { get; set; }

    public virtual Application Application { get; set; }

    public virtual Sparepart SparePart { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}