// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DataAccessLayer.Models;

public partial class User
{
    public int UserId { get; set; }

    public string NationalNo { get; set; }

    public string Name { get; set; }

    public string Role { get; set; }

    public int AccessRight { get; set; }

    public string Password { get; set; }
    [JsonIgnore]
    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}