// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Vehicle
{
    public short VehicleId { get; set; }

    public string BrandName { get; set; }

    public string ModelName { get; set; }

    public string PlateNumbers { get; set; }

    public sbyte VehicleType { get; set; }

    public string AssociatedHospital { get; set; }

    public string AssociatedTask { get; set; }

    public string Status { get; set; }

    public sbyte FuelType { get; set; }

    public sbyte FuelConsumptionRate { get; set; }

    public sbyte OilConsumptionRate { get; set; }

    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();

    public virtual ICollection<Consumableswithdrawapplication> Consumableswithdrawapplications { get; set; } = new List<Consumableswithdrawapplication>();

    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();

    public virtual ICollection<Sparepartswithdrawapplication> Sparepartswithdrawapplications { get; set; } = new List<Sparepartswithdrawapplication>();
}